name: render

on: push

jobs:
  all:
    name: Render cheat sheets
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - run: sudo apt-get install chromium-browser
      - run: Rscript -e "install.packages('remotes')"
      - run: >
          Rscript -e "install.packages(c('mlr3', 'mlr3tuning',
          'mlr3fselect', 'mlr3pipelines'))"
      - run: Rscript -e "remotes::install_github('be-marc/cheatdown')"
      - run: >
          Rscript -e "cheatdown::print_pdf('mlr3/mlr3.Rmd',
          'pdf/mlr3.pdf', chrome = FALSE)"
      - run: >
          Rscript -e "cheatdown::print_pdf('mlr3tuning/mlr3tuning.Rmd',
          'pdf/mlr3tuning.pdf', chrome = FALSE)"
      - run: >
          Rscript -e "cheatdown::print_pdf('mlr3fselect/mlr3fselect.Rmd',
          'pdf/mlr3fselect.pdf', chrome = FALSE)"
      - run: >
          Rscript -e "cheatdown::print_pdf('mlr3pipelines/mlr3pipelines.Rmd',
          'pdf/mlr3pipelines.pdf', chrome = FALSE)"

      - uses: actions/upload-artifact@v2
        with:
          name: cheatsheet
          path: |
            pdf/
            mlr3/
            mlr3tuning/
            mlr3fselect/
            mlr3pipelines/
